"""One-time manual token for the 'user gave the order directly' path (SPEC S7).

The MCP tool `sag_publish` has NO manual flag — there is no way for the model
to self-report "the user gave the order" and have the engine trust the model's
word. The real manual path goes through:

  slash command `/sag-publish <path|glob>` (typed by a HUMAN)
    -> the UserPromptSubmit hook mints a token ONLY when the prompt matches this
       exact command shape
    -> the token is bound to hash(args), single-use, short TTL
    -> the agent calls the CLI/tool with the token -> the engine consumes it
       itself and determines the initiator

The token is bound to the args themselves (path/glob) so it can't be reused
for a different path — otherwise, a token valid for "publish A" could be used
to "publish B" in the same turn.
"""
from __future__ import annotations

import hashlib
import json
import time

from . import config

TOKEN_TTL_SECONDS = 300


def _args_hash(args_str: str) -> str:
    return hashlib.sha256(args_str.strip().encode("utf-8")).hexdigest()


def mint(args_str: str, token: str) -> dict:
    """Called by the UserPromptSubmit hook when the prompt matches `/sag-publish ...`.

    `token` is generated by the hook using secrets.token_urlsafe (the hook runs
    in the harness's own process, not in this module, to keep manual.py pure
    and testable without simulating the hook).
    """
    rec = {
        "token": token,
        "args_hash": _args_hash(args_str),
        "minted_at": time.time(),
        "expires_at": time.time() + TOKEN_TTL_SECONDS,
    }
    path = _token_path(token)
    path.write_text(json.dumps(rec), encoding="utf-8")
    return rec


def _token_path(token: str):
    # `token-` prefixed, not bare `{token}.json` — config.session_dir() is shared
    # scratch space for other hooks too (post_tool_use_nudge's per-session nudge
    # cache, session_end_backstop's per-session notified cache), which also write
    # `*.json` there but hold a list, not a token record. cleanup_expired() globs
    # this directory; without the prefix it can pick up one of those files and
    # crash on `.get()` (found live, 2026-08-02, via `sagctl doctor`).
    return config.session_dir() / f"token-{token}.json"


def consume(token: str, args_str: str) -> bool:
    """Single-use: delete the file IMMEDIATELY on read, regardless of outcome —
    the token is used exactly once whether it succeeds or fails, preventing
    brute-force retries against the same token.
    """
    path = _token_path(token)
    if not path.exists():
        return False
    try:
        rec = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        path.unlink(missing_ok=True)
        return False
    path.unlink(missing_ok=True)
    if time.time() > rec.get("expires_at", 0):
        return False
    if rec.get("args_hash") != _args_hash(args_str):
        return False
    return True


def cleanup_expired() -> int:
    """Clean up leftover expired tokens (crashed before being consumed). Called from `sagctl doctor`."""
    removed = 0
    now = time.time()
    for path in config.session_dir().glob("token-*.json"):
        try:
            rec = json.loads(path.read_text(encoding="utf-8"))
            if now > rec.get("expires_at", 0):
                path.unlink(missing_ok=True)
                removed += 1
        except (json.JSONDecodeError, OSError):
            path.unlink(missing_ok=True)
            removed += 1
    return removed
